### ISSUE TITLE
Is the rest api available?

### ISSUE THREAD

**Issue by nkaramolegos** [blockchaind/hyperledger-fabric-v2-kubernetes-dev#13]
As I can see in api/api-k8s.yaml the image of the REST API server is blockchaindio/hlf-api. Is this code available? I am looking to build my rest api for deploy and maintain of HLF

**Comment by blockchaind** [comment]
@nkaramolegos, you don't have to use blockchaindio/hlf-api image. Just build the Dockerfile in `api` directory and push it to an image registry ie docker hub.

**Comment by nkaramolegos** [comment]
Oh nice thanks. One more question you are using cryptogen and not fabric-ca. Correct?

**Comment by blockchaind** [comment]
Well it's a dev env setup in the first place anyway. Ideally one would use fabric-ca.
